image: davetucker/golang-ci:1.3
git:
  path: github.com/socketplane/socketplane 
script:
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/mattn/goveralls
  - sh tools/run-tests.sh 
  - sh tools/combine-coverage.sh
  - sh tools/publish-coverage.sh
services:
  - davetucker/drone-ovs
docker:
  - net: host
notify:
  slack:
    webhook_url: '$$slack_url'
    on_started: false
    on_success: true
    on_failure: true
